## Team work that fosters reproducibility

Research is increasingly being conducted in teams. The bigger and more complex
the team, the more complicated it can be to work in a reproducible fashion.
Thinking about how to set up a team to foster reproducibility is essential, 
because a bigger team can also mean that reproducibility becomes easier. If the
whole team works together, their diverse skills will help in creating a thriving
and reproducible research project.

In *The Turing Way's* [Guide to Planning a Community](https://the-turing-way.netlify.app/collaboration/new-community/new-community-guide.html)
they discuss 8 steps, that work well for a broad range of research teams:

1. Choose a Communication Platform (e.g. GitHub + Chat + Website)
2. Provide a Project Summary File (e.g. README.md)
3. Select a Code of Conduct 
4. Provide Contribution Guidelines and Interaction Pathways
5. Create a Basic Management/Leadership Structure (roles)
6. Provide Contact Details Wherever Useful (email address to role)
7. Identify Failed Approaches, and Stop Them
8. Have Documentation (e.g. a wiki) and Dissemination Plans for Your Project (e.g. publication on Zenodo)

Note that there are two important parts fo thriving teams:

- Documents (wiki, checklist, ...)
- Roles of people (research software engineer, welcome team, ...)

How is your team set up? Which of the 8 steps are unclear to you?