# Reproducible research and how to get there

::: {.callout-note}
## Learning targets

- You will know what reproducibility is, what the hurdles are, and why it is important for research.

- You will know about the FAIR data principles and be able to discuss the issues in implementing them.

- You will be able to discuss the complexity of collaboration in research and communicating and working more effectively is important for good research.
:::



::: {.callout-caution}
## Tasks

Read this chapter and watch this week's videos. 
Afterwards go through the following assignments:

- What questions came up for you while watching the videos and going through the booklet?
- What are your personal hurdles for reproducible research? What can you do to address them?
- What are hurdles for you in producing FAIR data? What can you do for the data you work with?
- Which of the points in the 8 steps for Planning a Community does your research team already check off? Which should be discussed? If possible, bring open points to your team meeting. 

Bring any questions and problems that come up to the weekly meeting.
:::






