project:
  type: book

book:
  title: "BERD Course: Make Your Research Reproducible"
  author: "Heidi Seibold"
  chapters:
    - index.qmd
    - intro.qmd
    - 1-reproducible-research.qmd
    - 2-project-organization.qmd
    - 3-computational-workflows.qmd
    - 4-publishing-research.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt



