project:
  type: book

book:
  title: "BERD Course: Make Your Research Reproducible"
  author: "Heidi Seibold"
  chapters:
  - part: index.qmd
    chapters:
      - intro.qmd
  - part: 1-reproducible-research.qmd
    chapters:
    - 1-1-what-is-reproducible-research.qmd
    - 1-2-hurdles.qmd
    - 1-3-fair.qmd
    - 1-4-team-work.qmd
  - part: 2-project-organization.qmd
    chapters:
    - 2-1-naming.qmd
    - 2-2-organisation.qmd
    - 2-3-documentation.qmd
  - part: 3-computational-workflows.qmd
    chapters:
    - 3-1-version-control.qmd
    - 3-2-stabilize.qmd
    - 3-3-automate.qmd
  - part: 4-publishing-research.qmd
    chapters:
    - 4-1-licensing.qmd
    - 4-2-where-to-publish.qmd
    - 4-3-fair-revisited.qmd
  - part: summary.qmd
    chapters:
    - references.qmd
  navbar: 
    logo: images/Logo_BERD_Academy.png

bibliography: references.bib

format:
  html:
    theme: flatly
    
number-depth: 2

